[package]
name = "mkfs-modernfs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mkfs-modernfs"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
indicatif = "0.17"
colored = "2.0"