[package]
name = "fsck-modernfs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fsck-modernfs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"